# ---- FASE DE BUILD ----
FROM node:20-alpine AS build

WORKDIR /app

# Copia configs
COPY package*.json ./
RUN npm install

# Copia todo o código
COPY . .

# Builda o projeto para produção
RUN npm run build

# ---- FASE DE SERVIDOR ----
FROM node:20-alpine AS prod

WORKDIR /app

# Instala servidor estático
RUN npm install -g serve

# Copia os arquivos buildados
COPY --from=build /app/dist ./dist

# Porta em que o serve vai rodar
EXPOSE 4173

# Sobe o servidor
CMD ["serve", "-s", "dist", "-l", "4173"]
