FROM node:20-alpine

# Instala o cliente PostgreSQL (necessário pro pg_isready)
RUN apk add --no-cache postgresql-client

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

RUN chmod +x start.sh

EXPOSE 8080

CMD ["sh", "./start.sh"]
